project_id = "jgrqriiosiebhtkekgfo"

[functions.vendor-signup]
verify_jwt = false

[functions.guest-auth]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false

[functions.steadfast-webhook]
verify_jwt = false
