
UPDATE products SET description_bn = 'ঘরে তৈরি খাঁটি আমের আচার, দেশি মসলা দিয়ে প্রস্তুত। আমাদের আমের আচার সম্পূর্ণ হাতে তৈরি এবং কোনো প্রকার কেমিক্যাল বা প্রিজারভেটিভ ব্যবহার করা হয়নি। সরিষার তেল, মেথি, কালোজিরা, মরিচ ও লবণ দিয়ে ঐতিহ্যবাহী রেসিপিতে তৈরি এই আচার আপনার খাবারের স্বাদ বাড়িয়ে তুলবে। গরম ভাতের সাথে বা পরোটার সাথে এই আচারের জুড়ি নেই।', description = 'Authentic homemade mango pickle prepared with traditional Bengali spices. Our mango pickle is completely handmade without any chemicals or preservatives. Made with mustard oil, fenugreek, black cumin, chili and salt in a traditional recipe, this pickle will enhance the taste of your food.' WHERE id = '4b37f695-7dfc-427a-8391-dabe2e238f05';

UPDATE products SET description_bn = 'টাটকা তেঁতুল দিয়ে তৈরি টক-ঝাল আচার। এই আচার তৈরিতে ব্যবহার করা হয়েছে পাকা তেঁতুল, সরিষার তেল, পাঁচফোড়ন, শুকনো মরিচ এবং লবণ। তেঁতুলের আচার খাবারে একটি অনন্য টক স্বাদ যোগ করে। ভাত, খিচুড়ি বা যেকোনো খাবারের সাথে এই আচার পরিবেশন করতে পারেন। সম্পূর্ণ প্রাকৃতিক উপাদানে তৈরি।', description = 'Tangy tamarind pickle made with fresh ripe tamarind, mustard oil, panch phoron, dried chili and salt. This pickle adds a unique sour flavor to your meals. Can be served with rice, khichuri or any dish. Made entirely with natural ingredients.' WHERE id = '8110519d-4bbf-411f-ad17-8f5dcc4a871d';

UPDATE products SET description_bn = 'সরিষার তেলে তৈরি ঝাল রসুনের আচার। তাজা রসুন, সরিষার তেল, মরিচের গুঁড়া, হলুদ এবং লবণ দিয়ে তৈরি এই আচার স্বাদে অতুলনীয়। রসুনের আচার শুধু সুস্বাদুই নয়, স্বাস্থ্যের জন্যও উপকারী। এটি রোগ প্রতিরোধ ক্ষমতা বাড়ায় এবং হজমে সহায়তা করে। প্রতিদিনের খাবারের সাথে অল্প পরিমাণ রসুনের আচার খেলে শরীর সুস্থ থাকে।', description = 'Spicy garlic pickle made with mustard oil. Prepared with fresh garlic, mustard oil, chili powder, turmeric and salt. Garlic pickle is not only delicious but also beneficial for health. It boosts immunity and aids digestion.' WHERE id = 'decf1a5c-16db-488b-aec6-ed508373ec7e';

UPDATE products SET description_bn = 'রাজশাহীর বিখ্যাত প্রিমিয়াম হিমসাগর আম। এই আম মিষ্টি, রসালো এবং অত্যন্ত সুগন্ধি। রাজশাহীর উর্বর মাটিতে জন্মানো এই আম সারা বাংলাদেশে বিখ্যাত। কোনো প্রকার কার্বাইড বা কেমিক্যাল ব্যবহার করা হয়নি। গাছ পাকা আম সরাসরি বাগান থেকে সংগ্রহ করে আপনার দোরগোড়ায় পৌঁছে দেওয়া হয়। প্রতিটি আম হাতে বাছাই করা এবং মান নিয়ন্ত্রিত।', description = 'Premium Himsagar mangoes from Rajshahi. These mangoes are sweet, juicy and extremely aromatic. Grown in the fertile soil of Rajshahi, these mangoes are famous across Bangladesh. No carbide or chemicals used. Tree-ripened mangoes collected directly from orchards and delivered to your doorstep.' WHERE id = 'ea0ac68e-44db-40fa-b771-ed8acd041031';

UPDATE products SET description_bn = 'মিষ্টি ও সুগন্ধি ল্যাংড়া আম। ল্যাংড়া আম বাংলাদেশের অন্যতম জনপ্রিয় আমের জাত। এই আমের বিশেষত্ব হলো এর অনন্য মিষ্টি স্বাদ এবং মনমাতানো সুগন্ধ। সম্পূর্ণ প্রাকৃতিকভাবে পাকানো, কোনো রাসায়নিক দ্রব্য ব্যবহার করা হয়নি। তাজা অবস্থায় সরাসরি বাগান থেকে সংগ্রহ করে যত্নসহকারে প্যাকেজিং করে পাঠানো হয়।', description = 'Sweet and aromatic Langra mangoes. Langra is one of the most popular mango varieties in Bangladesh. The specialty of this mango is its unique sweet taste and captivating aroma. Completely naturally ripened, no chemicals used. Collected fresh from orchards and carefully packaged for delivery.' WHERE id = '4945f66e-99a9-48cb-bba9-3c897c192f96';
