// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmfbirdlpfpuoumxgcfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZmJpcmRscGZwdW91bXhnY2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NDU4NDksImV4cCI6MjA5MjMyMTg0OX0.u_me4LRrKCQ3ThQ8zBKMVjWKj7EyrAm4M3Y2qh6MRyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});