// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqdirlxffyfplbhiadou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxZGlybHhmZnlmcGxiaGlhZG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0ODA0NTEsImV4cCI6MjA5NDA1NjQ1MX0.08CygMcgDNZ53TYRivyBPuaLkGcSQyG1yATGZsBnyF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});